/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://rqyd4trj3zch3bumi3ce7ksqjq.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-knb5pw3p4rfc5bii2aiuv5eox4",
    "aws_cognito_identity_pool_id": "us-east-1:dad597d1-e3d0-47c9-8241-4789411253d5",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_sFxluPu3o",
    "aws_user_pools_web_client_id": "5tjedv1902bkpd51pq841pk87c",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "financetracker2360d09927a0346a8934cad9be891d5fbecd2b-main",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
